const carsDatabase = [
    {
        "id": 1,
        "make": "Volkswagen",
        "model": "Golf GTI",
        "aliases": ["vw"],
        "generation": "Mk8.5",
        "modelYears": "2024-present",
        "year": 2024,
        "hp": 241,
        "zeroToSixty": 5.9,
        "topSpeed": 155,
        "cylinders": 4,
        "displacement": 2,
        "enginePlacement": "Front",
        "drivetrain": "FWD",
        "weight": 3232
    },
    {
        "id": 2,
        "make": "Volkswagen",
        "model": "Golf GTI",
        "aliases": ["vw"],
        "generation": "Mk8",
        "modelYears": "2020-2024",
        "year": 2022,
        "hp": 241,
        "zeroToSixty": 5.9,
        "topSpeed": 155,
        "cylinders": 4,
        "displacement": 2,
        "enginePlacement": "Front",
        "drivetrain": "FWD",
        "weight": 3225
    },
    {
        "id": 3,
        "make": "Volkswagen",
        "model": "Golf GTI",
        "aliases": ["vw"],
        "generation": "Mk7.5",
        "modelYears": "2017-2020",
        "year": 2018,
        "hp": 228,
        "zeroToSixty": 5.9,
        "topSpeed": 155,
        "cylinders": 4,
        "displacement": 2,
        "enginePlacement": "Front",
        "drivetrain": "FWD",
        "weight": 3082
    },
    {
        "id": 4,
        "make": "Volkswagen",
        "model": "Golf GTI",
        "aliases": ["vw"],
        "generation": "Mk7",
        "modelYears": "2015-2017",
        "year": 2017,
        "hp": 220,
        "zeroToSixty": 5.9,
        "topSpeed": 155,
        "cylinders": 4,
        "displacement": 2,
        "enginePlacement": "Front",
        "drivetrain": "FWD",
        "weight": 3075
    },
    {
        "id": 5,
        "make": "Porsche",
        "model": "911 Carrera",
        "generation": "992.2",
        "modelYears": "2025-present",
        "year": 2025,
        "hp": 388,
        "zeroToSixty": 3.9,
        "topSpeed": 183,
        "cylinders": 6,
        "displacement": 3,
        "enginePlacement": "Rear",
        "drivetrain": "RWD",
        "weight": 3472
    },
    {
        "id": 6,
        "make": "Porsche",
        "model": "911 Carrera",
        "generation": "992",
        "modelYears": "2019-2024",
        "year": 2024,
        "hp": 379,
        "zeroToSixty": 4,
        "topSpeed": 182,
        "cylinders": 6,
        "displacement": 3,
        "enginePlacement": "Rear",
        "drivetrain": "RWD",
        "weight": 3354
    },
    {
        "id": 7,
        "make": "Porsche",
        "model": "911 Carrera",
        "generation": "991.2",
        "modelYears": "2016-2019",
        "year": 2016,
        "hp": 370,
        "zeroToSixty": 4,
        "topSpeed": 183,
        "cylinders": 6,
        "displacement": 3,
        "enginePlacement": "Rear",
        "drivetrain": "RWD",
        "weight": 3219
    },
    {
        "id": 8,
        "make": "Porsche",
        "model": "911 Carrera",
        "generation": "991.1",
        "modelYears": "2012-2016",
        "year": 2012,
        "hp": 350,
        "zeroToSixty": 4.4,
        "topSpeed": 179,
        "cylinders": 6,
        "displacement": 3.4,
        "enginePlacement": "Rear",
        "drivetrain": "RWD",
        "weight": 3042
    },
    {
        "id": 9,
        "make": "Porsche",
        "model": "911 Carrera",
        "generation": "997.2",
        "modelYears": "2009-2012",
        "year": 2009,
        "hp": 345,
        "zeroToSixty": 4.7,
        "topSpeed": 179,
        "cylinders": 6,
        "displacement": 3.6,
        "enginePlacement": "Rear",
        "drivetrain": "RWD",
        "weight": 3075
    },
    {
        "id": 10,
        "make": "Porsche",
        "model": "911 Carrera",
        "generation": "997.1",
        "modelYears": "2005-2008",
        "year": 2008,
        "hp": 325,
        "zeroToSixty": 4.8,
        "topSpeed": 177,
        "cylinders": 6,
        "displacement": 3.6,
        "enginePlacement": "Rear",
        "drivetrain": "RWD",
        "weight": 3075
    },
    {
        "id": 11,
        "make": "Porsche",
        "model": "911 Carrera",
        "generation": "997.2",
        "modelYears": "2009-2012",
        "year": 2012,
        "hp": 345,
        "zeroToSixty": 4.5,
        "topSpeed": 179,
        "cylinders": 6,
        "displacement": 3.6,
        "enginePlacement": "Rear",
        "drivetrain": "RWD",
        "weight": 3186
    }
];