export const APP_NAME = 'AutoSnipe'
export const APP_VERSION = '1.1.0'
export const ACCENT_COLOR = '#FF6B00'
export const FREE_SEARCHES = 1
export const SLOT_PRICE = 1
export const SLOT_PRICE_LABEL = '/mo'
export const SUPPORTED_CURRENCIES = ['gbp', 'usd', 'eur']
export const CURRENCY_SYMBOLS = { gbp: '£', usd: '$', eur: '€' }
export const POLL_INTERVAL_MINUTES = 5
export const MAX_AGENT_ITERATIONS = 8
export const QUIET_START_UTC = 2   // Hour (UTC) to slow polling to once/hour at :59
export const QUIET_END_UTC = 5     // Hour (UTC) to resume normal polling
