export const APP_NAME = 'AutoSnipe'
export const APP_VERSION = '1.1.0'
export const ACCENT_COLOR = '#FF6B00'
export const FREE_SEARCHES = 1
export const SLOT_PRICE = 1
export const SUPPORTED_CURRENCIES = ['gbp', 'usd', 'eur']
export const CURRENCY_SYMBOLS = { gbp: '£', usd: '$', eur: '€' }
export const POLL_INTERVAL_HOURS = 3
export const MAX_AGENT_ITERATIONS = 8
export const NIGHT_SKIP_START = 0  // Hour (Europe/London) to start skipping polls
export const NIGHT_SKIP_END = 6    // Hour (Europe/London) to resume polls
